"""Добавление таблицы telegram_users.

Revision ID: 1a2b3c4d5e6f
Revises: 0d5b780bf7ec
Create Date: 2024-09-28 19:43:12.156310
"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '1a2b3c4d5e6f'
down_revision = '0d5b780bf7ec'
branch_labels = None
depends_on = None


def upgrade() -> None:
    """Создание таблицы telegram_users."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'telegram_users',
        sa.Column('id', sa.Integer(), nullable=False, primary_key=True),
        sa.Column('telegram_id', sa.BigInteger(), unique=True, nullable=False),
        sa.Column('first_name', sa.String(length=100), nullable=False),
        sa.Column('last_name', sa.String(length=100), nullable=True),
        sa.Column(
            'username', sa.String(length=100), unique=True, nullable=True
        ),
        sa.Column('language_code', sa.String(length=10), nullable=True),
        sa.Column('is_premium', sa.Boolean(), default=False, nullable=True),
        sa.Column(
            'added_to_attachment_menu',
            sa.Boolean(),
            default=False,
            nullable=True,
        ),
        sa.Column(
            'created_on', sa.DateTime(), nullable=True, default=sa.func.now()
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Удаление таблицы telegram_users."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('telegram_users')
    # ### end Alembic commands ###
